version: 3.9.1.{build}

skip_branch_with_pr: false
skip_commits:
  message: /!nobuild/
skip_tags: false

environment:
  LUAROCKS_VER: 2.4.1
  matrix:
  - LUA_VER: 5.1.5

matrix:
  allow_failures:
    - configuration: 2010
      platform: x64
    - configuration: 2008
      platform: x64
    - configuration: MinGW
      platform: x64



# Abuse this section so we can have a matrix with different Compiler versions
# Is there a better way? Like injecting an array in the matrix?
configuration:
  - Build

platform:
  - x64

init:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  
install:
  - cmd: choco install 7zip.commandline
  # Make compiler command line tools available
  - call .appveyor\set_compiler_env.bat
  # Setup Lua development/build environment
  - call .appveyor\install.bat
  # Install luasrcdiet to strip lua source code from comments etc
  - cmd: luarocks install luasrcdiet
  - cmd: luarocks install checks
  - cmd: luarocks install luadocumentor
  

cache:
  - C:\ProgramData\chocolatey\lib
  - C:\ProgramData\chocolatey\bin
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml



for:

# override settings for `master` branch
-
  branches:
    only:
      - master



  build_script:
    - cmd: echo "Build for master branch"
    - cmd: moose_create.bat %APPVEYOR_REPO_COMMIT%
    - cmd: luadocumentor.bat -f doc -d "./docs/Documentation" -s "./docs/Stylesheet/stylesheet.css" "./Moose Development/Moose"

-
  branches:
    only:
      - /Release.*/

  build_script:
	  - luarocks make rockspecs/foo-scm-0.rockspec --local
	  - cmd: echo "Build for a release branch"
	  - cmd: moose_create.bat %APPVEYOR_REPO_COMMIT%
	  - cmd: luasrcdiet.bat --basic --opt-emptylines "Moose Mission Setup"\Moose.lua
	  - git clone https://github.com/FlightControl-Master/MOOSE_MISSIONS.git missions
	  - cmd: Moose_update_missions.bat missions


test: off

artifacts:
  - path: 'Moose Mission Setup/Moose.lua'
    name: moose.lua
  - path: 'Moose Mission Setup/Moose_.lua'
    name: moose_.lua
  - path: '**\*.miz'
    name: miz

